"""Migration 2.

Revision ID: 1bf3547d9e13
Revises: b748032139ab
Create Date: 2021-08-26 17:06:41.152445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bf3547d9e13'
down_revision = 'b748032139ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('electionparticipants', sa.Column('serialNumber', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('electionparticipants', 'serialNumber')
    # ### end Alembic commands ###
