"""Migration 4.

Revision ID: 1e16f53d887e
Revises: d60b676f1166
Create Date: 2021-08-26 23:17:13.560853

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1e16f53d887e'
down_revision = 'd60b676f1166'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('votes', sa.Column('poolNumber', sa.Integer(), nullable=False))
    op.add_column('votes', sa.Column('reason', sa.String(length=256), nullable=True))
    op.drop_column('votes', 'participantNumber')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('votes', sa.Column('participantNumber', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('votes', 'reason')
    op.drop_column('votes', 'poolNumber')
    # ### end Alembic commands ###
