"""Migration.

Revision ID: b748032139ab
Revises: 
Create Date: 2021-08-25 23:38:05.681281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b748032139ab'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('elections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start', sa.String(length=256), nullable=False),
    sa.Column('end', sa.String(length=256), nullable=False),
    sa.Column('individual', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('individual', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('electionparticipants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('electionId', sa.Integer(), nullable=False),
    sa.Column('participantId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['electionId'], ['elections.id'], ),
    sa.ForeignKeyConstraint(['participantId'], ['participants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guid', sa.String(length=256), nullable=False),
    sa.Column('participantNumber', sa.Integer(), nullable=False),
    sa.Column('jmbgElectionOffical', sa.String(length=256), nullable=False),
    sa.Column('idElection', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idElection'], ['elections.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('votes')
    op.drop_table('electionparticipants')
    op.drop_table('participants')
    op.drop_table('elections')
    # ### end Alembic commands ###
