"""Migration 6

Revision ID: be06f8e35736
Revises: 573e05543dc9
Create Date: 2021-08-27 17:05:53.523371

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'be06f8e35736'
down_revision = '573e05543dc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('votes', sa.Column('electionOfficialJmbg', sa.String(length=256), nullable=False))
    op.drop_column('votes', 'jmbgElectionOffical')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('votes', sa.Column('jmbgElectionOffical', mysql.VARCHAR(length=256), nullable=False))
    op.drop_column('votes', 'electionOfficialJmbg')
    # ### end Alembic commands ###
