"""Migration 7

Revision ID: c1e545c147e6
Revises: be06f8e35736
Create Date: 2021-08-27 17:07:09.911701

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c1e545c147e6'
down_revision = 'be06f8e35736'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('votes', sa.Column('pollNumber', sa.Integer(), nullable=False))
    op.drop_column('votes', 'poolNumber')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('votes', sa.Column('poolNumber', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('votes', 'pollNumber')
    # ### end Alembic commands ###
