"""Migration 3.

Revision ID: d60b676f1166
Revises: 1bf3547d9e13
Create Date: 2021-08-26 21:56:46.287832

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd60b676f1166'
down_revision = '1bf3547d9e13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('electionparticipants', sa.Column('poolNumber', sa.Integer(), nullable=False))
    op.drop_column('electionparticipants', 'serialNumber')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('electionparticipants', sa.Column('serialNumber', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('electionparticipants', 'poolNumber')
    # ### end Alembic commands ###
